#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CanteenSystem.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CanteenDB")]
	public partial class CanteenOrderDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertCanteenOrder(CanteenOrder instance);
    partial void UpdateCanteenOrder(CanteenOrder instance);
    partial void DeleteCanteenOrder(CanteenOrder instance);
    #endregion
		
		public CanteenOrderDataContext() : 
				base(global::CanteenSystem.Model.Properties.Settings.Default.CanteenDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CanteenOrderDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CanteenOrderDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CanteenOrderDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CanteenOrderDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CanteenOrder> CanteenOrder
		{
			get
			{
				return this.GetTable<CanteenOrder>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CanteenOrder")]
	public partial class CanteenOrder : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CanteenOrderKeyID;
		
		private string _CanteenOrderName;
		
		private System.Nullable<double> _CanteenOrderMoney;
		
		private System.Nullable<int> _CanteenOrderCount;
		
		private string _Memo;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCanteenOrderKeyIDChanging(string value);
    partial void OnCanteenOrderKeyIDChanged();
    partial void OnCanteenOrderNameChanging(string value);
    partial void OnCanteenOrderNameChanged();
    partial void OnCanteenOrderMoneyChanging(System.Nullable<double> value);
    partial void OnCanteenOrderMoneyChanged();
    partial void OnCanteenOrderCountChanging(System.Nullable<int> value);
    partial void OnCanteenOrderCountChanged();
    partial void OnMemoChanging(string value);
    partial void OnMemoChanged();
    #endregion
		
		public CanteenOrder()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CanteenOrderKeyID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CanteenOrderKeyID
		{
			get
			{
				return this._CanteenOrderKeyID;
			}
			set
			{
				if ((this._CanteenOrderKeyID != value))
				{
					this.OnCanteenOrderKeyIDChanging(value);
					this.SendPropertyChanging();
					this._CanteenOrderKeyID = value;
					this.SendPropertyChanged("CanteenOrderKeyID");
					this.OnCanteenOrderKeyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CanteenOrderName", DbType="VarChar(50)")]
		public string CanteenOrderName
		{
			get
			{
				return this._CanteenOrderName;
			}
			set
			{
				if ((this._CanteenOrderName != value))
				{
					this.OnCanteenOrderNameChanging(value);
					this.SendPropertyChanging();
					this._CanteenOrderName = value;
					this.SendPropertyChanged("CanteenOrderName");
					this.OnCanteenOrderNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CanteenOrderMoney", DbType="Float")]
		public System.Nullable<double> CanteenOrderMoney
		{
			get
			{
				return this._CanteenOrderMoney;
			}
			set
			{
				if ((this._CanteenOrderMoney != value))
				{
					this.OnCanteenOrderMoneyChanging(value);
					this.SendPropertyChanging();
					this._CanteenOrderMoney = value;
					this.SendPropertyChanged("CanteenOrderMoney");
					this.OnCanteenOrderMoneyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CanteenOrderCount", DbType="Int")]
		public System.Nullable<int> CanteenOrderCount
		{
			get
			{
				return this._CanteenOrderCount;
			}
			set
			{
				if ((this._CanteenOrderCount != value))
				{
					this.OnCanteenOrderCountChanging(value);
					this.SendPropertyChanging();
					this._CanteenOrderCount = value;
					this.SendPropertyChanged("CanteenOrderCount");
					this.OnCanteenOrderCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Memo", DbType="VarChar(500)")]
		public string Memo
		{
			get
			{
				return this._Memo;
			}
			set
			{
				if ((this._Memo != value))
				{
					this.OnMemoChanging(value);
					this.SendPropertyChanging();
					this._Memo = value;
					this.SendPropertyChanged("Memo");
					this.OnMemoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
