<?xml version="1.0" encoding="utf-8"?><Database Name="CanteenDB" Class="MenuOrder_RDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=PHQ\SQLEXPRESS;Initial Catalog=CanteenDB;Persist Security Info=True;User ID=sa" SettingsObjectName="CanteenSystem.Model.Properties.Settings" SettingsPropertyName="CanteenDBConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.MenuOrder_R" Member="MenuOrder_R">
    <Type Name="MenuOrder_R">
      <Column Name="MenuOrderID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="OrderID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MenuName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Unit" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Quote" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Rate" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Price" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Count" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Money" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="InputDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Remark" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
</Database>