<?xml version="1.0" encoding="utf-8"?><Database Name="CanteenDB" Class="View_PriceDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=PHQ\SQLEXPRESS;Initial Catalog=CanteenDB;Persist Security Info=True;User ID=sa" SettingsObjectName="CanteenSystem.Model.Properties.Settings" SettingsPropertyName="CanteenDBConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.View_Price" Member="View_Price">
    <Type Name="View_Price">
      <Column Name="MenuID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PriceID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MenuName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Unit" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Quote" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Rate" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="InputDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>